language: java
jdk: 
- oraclejdk7
- openjdk6

notifications: 
  email: 
    recipients: 
    - justin.lee@mongodb.com
    on_success: change
    on_failure: always
  flowdock:
    secure: "Ziw1Be2tV0QAYuiYDrepfdNH/oBfNhnXFMji3AdRi6MePVpc6CtOOT/b9Fra\nQgMMrX3AHk/QIDo6QQx9/aVB3FS1fzOPGQkSsEZmiljZU7wZCct1sSSyttf/\nsRG0lyTnmgFNTHyTSDT3JbXAkyF/vJmG/JJJoBUZhmFxzR2fM0Q="

services: 
- mongodb

#branches: 
#  only: 
#  - master
#  - aggfluent

install: ./gradlew -q jar --stacktrace
script: ./gradlew -q check --stacktrace
